// Launch inventory, ported 1:1 from supabase/seed.sql for the no-Supabase
// local-only demo mode (see lib/local/store.ts).
import type { Listing } from '@/lib/types';

export const SEED_LISTINGS: Listing[] = [
  {
    id: 'l1', num: '01', title: 'Tørr kjellerbod på Grünerløkka', type: 'Bod', city: 'Oslo', area: 'Grünerløkka',
    distance: '0,4 km fra T-bane', size_m2: 6, size_m3: 14, price: 690, rating: 4.9, reviews: 47,
    ph: 'kjellerbod · 6 m²', avail: 'Ledig fra 15. mai',
    features: ['24/7 tilgang', 'Tørt og temperert', 'Kodelås', 'Kameraovervåket'],
    description: 'Romslig bod i kjelleren av en bygård fra 1898. Helt tørt og fritt for fukt — brukes selv til verktøy og sesongdekk. Egen kodelås, du kommer til når du vil.',
    access: 'Du får egen kodelås. Felles trapp opp til gateplan.',
    rules: ['Ikke brann-/eksplosjonsfarlig', 'Ikke matvarer', 'Forsikring opptil 50 000 kr'],
    coords: { x: 30, y: 40 }, host_name: 'Marte Hagen', host_initials: 'MH', host_since: '2024',
    host_verified: true, host_rating: 4.9, host_reviews: 47, owner_id: null, status: 'active', views: 128,
  },
  {
    id: 'l2', num: '02', title: 'Garasje ved Sognsvann', type: 'Garasje', city: 'Oslo', area: 'Nordberg',
    distance: 'Ved hovedvei', size_m2: 18, size_m3: 45, price: 1490, rating: 4.8, reviews: 28,
    ph: 'garasje · 18 m²', avail: 'Ledig nå',
    features: ['Bil-tilgang', 'Strømuttak', 'Egen port', '24/7 tilgang'],
    description: 'Frittstående enkeltgarasje på egen tomt. Kan brukes til bil, motorsykkel eller som rent lager. Strømuttak til lader. Asfaltert innkjørsel.',
    access: 'Egen port med portåpner. Asfaltert innkjørsel helt frem.',
    rules: ['Ingen overnatting', 'Ikke kjemikalielagring', 'Tobakksfritt'],
    coords: { x: 18, y: 22 }, host_name: 'Erik Bjerke', host_initials: 'EB', host_since: '2023',
    host_verified: true, host_rating: 4.8, host_reviews: 28, owner_id: null, status: 'active', views: 64,
  },
  {
    id: 'l3', num: '03', title: 'Loft over snekkerverksted', type: 'Loft', city: 'Oslo', area: 'Sagene',
    distance: '5 min fra Torshov', size_m2: 22, size_m3: 48, price: 1190, rating: 5.0, reviews: 63,
    ph: 'loft · 22 m²', avail: 'Ledig fra 1. juni',
    features: ['Tørt og temperert', 'Heisbar', 'Tilgang dagtid'],
    description: 'Stort åpent loft med god takhøyde i midten. Egnet for store gjenstander, sesongvarer og lett næringslager. Trebjelker og takvindu.',
    access: 'Heisbar opp. Tilgang man–lør 07–20.',
    rules: ['Ingen brennbar væske', 'Tilgang dagtid'],
    coords: { x: 44, y: 24 }, host_name: 'Sofia Lien', host_initials: 'SL', host_since: '2022',
    host_verified: true, host_rating: 5.0, host_reviews: 63, owner_id: null, status: 'active', views: 0,
  },
  {
    id: 'l4', num: '04', title: 'Container på industritomt', type: 'Container', city: 'Oslo', area: 'Alnabru',
    distance: 'Ved E6 — bil/lastebil', size_m2: 13, size_m3: 34, price: 1290, rating: 4.7, reviews: 112,
    ph: 'container · 20 fot', avail: 'Ledig nå',
    features: ['20-fots container', 'Bil-tilgang', '24/7 tilgang', 'Kameraovervåket'],
    description: 'Sjøcontainer på sikret industritomt, lett tilgjengelig med bil eller varebil. Belyst og kameraovervåket gårdsplass. Perfekt for bygningsmaterialer.',
    access: 'Eget hengelås-punkt. Kjør helt frem med varebil.',
    rules: ['Forsikring over 30 000 kr ordnes selv', 'Ikke beboelse'],
    coords: { x: 78, y: 62 }, host_name: 'Lager Øst AS', host_initials: 'LØ', host_since: '2021',
    host_verified: true, host_rating: 4.7, host_reviews: 112, owner_id: null, status: 'active', views: 0,
  },
  {
    id: 'l5', num: '05', title: 'Kjellerbod i bryggehus', type: 'Bod', city: 'Bergen', area: 'Bryggen',
    distance: '200 m fra Bryggen', size_m2: 5, size_m3: 11, price: 590, rating: 4.9, reviews: 31,
    ph: 'bod · 5 m²', avail: 'Ledig fra 2. juni',
    features: ['Tørt og temperert', 'Kodelås', 'Tilgang dagtid'],
    description: 'Liten, men tørr bod i et restaurert bryggehus. Eldre murvegger fra 1700-tallet, helt tørt. Sjarmerende beliggenhet med trange trapper.',
    access: 'Kodelås. Tilgang 07–22.',
    rules: ['Ingen overnatting', 'Tilgang 07–22'],
    coords: { x: 38, y: 32 }, host_name: 'Henrik Vassdal', host_initials: 'HV', host_since: '2024',
    host_verified: true, host_rating: 4.9, host_reviews: 31, owner_id: null, status: 'active', views: 0,
  },
  {
    id: 'l6', num: '06', title: 'Oppvarmet garasje på Landås', type: 'Garasje', city: 'Bergen', area: 'Landås',
    distance: '10 min fra sentrum', size_m2: 16, size_m3: 40, price: 1290, rating: 4.8, reviews: 22,
    ph: 'garasje · 16 m²', avail: 'Ledig nå',
    features: ['Bil-tilgang', 'Strømuttak', 'Tørt og temperert', '24/7 tilgang'],
    description: 'Oppvarmet garasje med automatisk port. Veldig tørr — perfekt for Bergens-vinteren. Egnet for bil, sykler og verktøy.',
    access: 'Automatisk port med fjernkontroll.',
    rules: ['Røykfritt', 'Ikke kjemikalier'],
    coords: { x: 60, y: 56 }, host_name: 'Ingrid Skog', host_initials: 'IS', host_since: '2023',
    host_verified: true, host_rating: 4.8, host_reviews: 22, owner_id: null, status: 'active', views: 0,
  },
  {
    id: 'l7', num: '07', title: 'Stort loft i sjøhus', type: 'Loft', city: 'Bergen', area: 'Sandviken',
    distance: 'Ved fjorden', size_m2: 28, size_m3: 65, price: 1390, rating: 5.0, reviews: 41,
    ph: 'loft · 28 m²', avail: 'Ledig fra 10. juni',
    features: ['Heisbar', 'Tilgang dagtid', 'Strømuttak'],
    description: 'Loft i historisk sjøhus med kraftige bjelker og god takhøyde. Bilkjøring helt frem til døren. Kan deles eller leies som helhet.',
    access: 'Heisbar. Bilkjøring til døren.',
    rules: ['Ingen brennbar væske', 'Tilgang 06–22'],
    coords: { x: 42, y: 22 }, host_name: 'Bjørn Krog', host_initials: 'BK', host_since: '2022',
    host_verified: true, host_rating: 5.0, host_reviews: 41, owner_id: null, status: 'active', views: 0,
  },
  {
    id: 'l8', num: '10', title: 'Dobbelgarasje på Lerkendal', type: 'Garasje', city: 'Trondheim', area: 'Lerkendal',
    distance: '10 min fra sentrum', size_m2: 20, size_m3: 50, price: 1390, rating: 4.7, reviews: 26,
    ph: 'garasje · 20 m²', avail: 'Ledig fra 8. juni',
    features: ['Bil-tilgang', 'Strømuttak', 'Egen port', '24/7 tilgang'],
    description: 'Romslig dobbelgarasje, plass til to biler eller bil + lager. Strømuttak og lys i hele garasjen.',
    access: 'Egen port med portåpner.',
    rules: ['Tobakksfritt', 'Ikke kjemikalier'],
    coords: { x: 40, y: 70 }, host_name: 'Tor Andersen', host_initials: 'TA', host_since: '2023',
    host_verified: true, host_rating: 4.7, host_reviews: 26, owner_id: null, status: 'active', views: 0,
  },
  {
    id: 'l9', num: '11', title: 'Industriseksjon ved Heimdal', type: 'Industri', city: 'Trondheim', area: 'Heimdal',
    distance: 'Ved E6, lasterampe', size_m2: 32, size_m3: 96, price: 2390, rating: 4.8, reviews: 64,
    ph: 'industri · 32 m²', avail: 'Ledig nå',
    features: ['Lasterampe', 'Bil-tilgang', 'Klimakontroll', '24/7 tilgang'],
    description: 'Profesjonelt mellomlager med rampe og truck-tilgang. Egnet for e-handel og småbedrift. Klimakontrollert.',
    access: 'Lasterampe. Bemannet 07–18.',
    rules: ['Bemannet 07–18', 'Ikke farlig gods'],
    coords: { x: 30, y: 84 }, host_name: 'Midt Lager AS', host_initials: 'ML', host_since: '2020',
    host_verified: true, host_rating: 4.8, host_reviews: 64, owner_id: null, status: 'active', views: 0,
  },
];
