// Demo dataset — the whole app runs on this, no database involved.
//
// Everything here is deterministic (no Date.now(), no randomness) so the
// server-rendered HTML and the client hydration match exactly. Mutations
// happen in memory in `lib/demo-store.ts` and last until the page reloads.

import type { Listing, Profile, RequestRow } from '@/lib/types';

/** The signed-in demo user. Owns two listings and rents one. */
export const DEMO_USER_ID = 'demo-user';

export const DEMO_PROFILE: Profile = {
  id: DEMO_USER_ID,
  name: 'Kari Nordmann',
  initials: 'KN',
  city: 'Oslo',
  member_since: '2024',
  rating: 4.9,
  tenancies: 1,
  as_host: 2,
};

export const DEMO_EMAIL = 'kari@nabolager.no';

/** Not signed in — browsing the public inventory. */
export const GUEST_PROFILE: Profile = {
  id: 'guest',
  name: 'Gjest',
  initials: 'G',
  city: 'Oslo',
  member_since: '2026',
  rating: 5.0,
  tenancies: 0,
  as_host: 0,
};

export const DEMO_LISTINGS: Listing[] = [
  {
    id: 'l1',
    num: '01',
    title: 'Tørr kjellerbod på Grünerløkka',
    type: 'Bod',
    city: 'Oslo',
    area: 'Grünerløkka',
    distance: '0,4 km fra T-bane',
    size_m2: 6,
    size_m3: 14,
    price: 690,
    rating: 4.9,
    reviews: 47,
    ph: 'kjellerbod · 6 m²',
    avail: 'Ledig fra 15. mai',
    features: ['24/7 tilgang', 'Tørt og temperert', 'Kodelås', 'Kameraovervåket'],
    description:
      'Romslig bod i kjelleren av en bygård fra 1898. Helt tørt og fritt for fukt — brukes selv til verktøy og sesongdekk. Egen kodelås, du kommer til når du vil.',
    access: 'Du får egen kodelås. Felles trapp opp til gateplan.',
    rules: ['Ikke brann-/eksplosjonsfarlig', 'Ikke matvarer', 'Forsikring opptil 50 000 kr'],
    coords: { x: 30, y: 40 },
    host_name: 'Marte Hagen',
    host_initials: 'MH',
    host_since: '2024',
    host_verified: true,
    host_rating: 4.9,
    host_reviews: 47,
    owner_id: null,
    status: 'active',
    views: 128,
  },
  {
    id: 'l2',
    num: '02',
    title: 'Garasje ved Sognsvann',
    type: 'Garasje',
    city: 'Oslo',
    area: 'Nordberg',
    distance: 'Ved hovedvei',
    size_m2: 18,
    size_m3: 45,
    price: 1490,
    rating: 4.8,
    reviews: 28,
    ph: 'garasje · 18 m²',
    avail: 'Ledig nå',
    features: ['Bil-tilgang', 'Strømuttak', 'Egen port', '24/7 tilgang'],
    description:
      'Frittstående enkeltgarasje på egen tomt. Kan brukes til bil, motorsykkel eller som rent lager. Strømuttak til lader. Asfaltert innkjørsel.',
    access: 'Egen port med portåpner. Asfaltert innkjørsel helt frem.',
    rules: ['Ingen overnatting', 'Ikke kjemikalielagring', 'Tobakksfritt'],
    coords: { x: 18, y: 22 },
    host_name: 'Erik Bjerke',
    host_initials: 'EB',
    host_since: '2023',
    host_verified: true,
    host_rating: 4.8,
    host_reviews: 28,
    owner_id: null,
    status: 'active',
    views: 64,
  },
  {
    id: 'l3',
    num: '03',
    title: 'Loft over snekkerverksted',
    type: 'Loft',
    city: 'Oslo',
    area: 'Sagene',
    distance: '5 min fra Torshov',
    size_m2: 22,
    size_m3: 48,
    price: 1190,
    rating: 5.0,
    reviews: 63,
    ph: 'loft · 22 m²',
    avail: 'Ledig fra 1. juni',
    features: ['Tørt og temperert', 'Heisbar', 'Tilgang dagtid'],
    description:
      'Stort åpent loft med god takhøyde i midten. Egnet for store gjenstander, sesongvarer og lett næringslager. Trebjelker og takvindu.',
    access: 'Heisbar opp. Tilgang man–lør 07–20.',
    rules: ['Ingen brennbar væske', 'Tilgang dagtid'],
    coords: { x: 44, y: 24 },
    host_name: 'Sofia Lien',
    host_initials: 'SL',
    host_since: '2022',
    host_verified: true,
    host_rating: 5.0,
    host_reviews: 63,
    owner_id: null,
    status: 'active',
    views: 91,
  },
  {
    id: 'l4',
    num: '04',
    title: 'Container på industritomt',
    type: 'Container',
    city: 'Oslo',
    area: 'Alnabru',
    distance: 'Ved E6 — bil/lastebil',
    size_m2: 13,
    size_m3: 34,
    price: 1290,
    rating: 4.7,
    reviews: 112,
    ph: 'container · 20 fot',
    avail: 'Ledig nå',
    features: ['20-fots container', 'Bil-tilgang', '24/7 tilgang', 'Kameraovervåket'],
    description:
      'Sjøcontainer på sikret industritomt, lett tilgjengelig med bil eller varebil. Belyst og kameraovervåket gårdsplass. Perfekt for bygningsmaterialer.',
    access: 'Eget hengelås-punkt. Kjør helt frem med varebil.',
    rules: ['Forsikring over 30 000 kr ordnes selv', 'Ikke beboelse'],
    coords: { x: 78, y: 62 },
    host_name: 'Lager Øst AS',
    host_initials: 'LØ',
    host_since: '2021',
    host_verified: true,
    host_rating: 4.7,
    host_reviews: 112,
    owner_id: null,
    status: 'active',
    views: 203,
  },
  {
    id: 'l5',
    num: '05',
    title: 'Kjellerbod i bryggehus',
    type: 'Bod',
    city: 'Bergen',
    area: 'Bryggen',
    distance: '200 m fra Bryggen',
    size_m2: 5,
    size_m3: 11,
    price: 590,
    rating: 4.9,
    reviews: 31,
    ph: 'bod · 5 m²',
    avail: 'Ledig fra 2. juni',
    features: ['Tørt og temperert', 'Kodelås', 'Tilgang dagtid'],
    description:
      'Liten, men tørr bod i et restaurert bryggehus. Eldre murvegger fra 1700-tallet, helt tørt. Sjarmerende beliggenhet med trange trapper.',
    access: 'Kodelås. Tilgang 07–22.',
    rules: ['Ingen overnatting', 'Tilgang 07–22'],
    coords: { x: 38, y: 32 },
    host_name: 'Henrik Vassdal',
    host_initials: 'HV',
    host_since: '2024',
    host_verified: true,
    host_rating: 4.9,
    host_reviews: 31,
    owner_id: null,
    status: 'active',
    views: 44,
  },
  {
    id: 'l6',
    num: '06',
    title: 'Oppvarmet garasje på Landås',
    type: 'Garasje',
    city: 'Bergen',
    area: 'Landås',
    distance: '10 min fra sentrum',
    size_m2: 16,
    size_m3: 40,
    price: 1290,
    rating: 4.8,
    reviews: 22,
    ph: 'garasje · 16 m²',
    avail: 'Ledig nå',
    features: ['Bil-tilgang', 'Strømuttak', 'Tørt og temperert', '24/7 tilgang'],
    description:
      'Oppvarmet garasje med automatisk port. Veldig tørr — perfekt for Bergens-vinteren. Egnet for bil, sykler og verktøy.',
    access: 'Automatisk port med fjernkontroll.',
    rules: ['Røykfritt', 'Ikke kjemikalier'],
    coords: { x: 60, y: 56 },
    host_name: 'Ingrid Skog',
    host_initials: 'IS',
    host_since: '2023',
    host_verified: true,
    host_rating: 4.8,
    host_reviews: 22,
    owner_id: null,
    status: 'active',
    views: 38,
  },
  {
    id: 'l7',
    num: '07',
    title: 'Stort loft i sjøhus',
    type: 'Loft',
    city: 'Bergen',
    area: 'Sandviken',
    distance: 'Ved fjorden',
    size_m2: 28,
    size_m3: 65,
    price: 1390,
    rating: 5.0,
    reviews: 41,
    ph: 'loft · 28 m²',
    avail: 'Ledig fra 10. juni',
    features: ['Heisbar', 'Tilgang dagtid', 'Strømuttak'],
    description:
      'Loft i historisk sjøhus med kraftige bjelker og god takhøyde. Bilkjøring helt frem til døren. Kan deles eller leies som helhet.',
    access: 'Heisbar. Bilkjøring til døren.',
    rules: ['Ingen brennbar væske', 'Tilgang 06–22'],
    coords: { x: 42, y: 22 },
    host_name: 'Bjørn Krog',
    host_initials: 'BK',
    host_since: '2022',
    host_verified: true,
    host_rating: 5.0,
    host_reviews: 41,
    owner_id: null,
    status: 'active',
    views: 57,
  },
  {
    id: 'l8',
    num: '10',
    title: 'Dobbelgarasje på Lerkendal',
    type: 'Garasje',
    city: 'Trondheim',
    area: 'Lerkendal',
    distance: '10 min fra sentrum',
    size_m2: 20,
    size_m3: 50,
    price: 1390,
    rating: 4.7,
    reviews: 26,
    ph: 'garasje · 20 m²',
    avail: 'Ledig fra 8. juni',
    features: ['Bil-tilgang', 'Strømuttak', 'Egen port', '24/7 tilgang'],
    description:
      'Romslig dobbelgarasje, plass til to biler eller bil + lager. Strømuttak og lys i hele garasjen.',
    access: 'Egen port med portåpner.',
    rules: ['Tobakksfritt', 'Ikke kjemikalier'],
    coords: { x: 40, y: 70 },
    host_name: 'Tor Andersen',
    host_initials: 'TA',
    host_since: '2023',
    host_verified: true,
    host_rating: 4.7,
    host_reviews: 26,
    owner_id: null,
    status: 'active',
    views: 33,
  },
  {
    id: 'l9',
    num: '11',
    title: 'Industriseksjon ved Heimdal',
    type: 'Industri',
    city: 'Trondheim',
    area: 'Heimdal',
    distance: 'Ved E6, lasterampe',
    size_m2: 32,
    size_m3: 96,
    price: 2390,
    rating: 4.8,
    reviews: 64,
    ph: 'industri · 32 m²',
    avail: 'Ledig nå',
    features: ['Lasterampe', 'Bil-tilgang', 'Klimakontroll', '24/7 tilgang'],
    description:
      'Profesjonelt mellomlager med rampe og truck-tilgang. Egnet for e-handel og småbedrift. Klimakontrollert.',
    access: 'Lasterampe. Bemannet 07–18.',
    rules: ['Bemannet 07–18', 'Ikke farlig gods'],
    coords: { x: 30, y: 84 },
    host_name: 'Midt Lager AS',
    host_initials: 'ML',
    host_since: '2020',
    host_verified: true,
    host_rating: 4.8,
    host_reviews: 64,
    owner_id: null,
    status: 'active',
    views: 88,
  },
  // ── The demo user's own listings — these fill "Mine annonser" ──────────────
  {
    id: 'l10',
    num: '12',
    title: 'Bod i bakgården på Torshov',
    type: 'Bod',
    city: 'Oslo',
    area: 'Torshov',
    distance: '300 m fra Torshovparken',
    size_m2: 8,
    size_m3: 19,
    price: 790,
    rating: 4.9,
    reviews: 12,
    ph: 'bod · 8 m²',
    avail: 'Ledig nå',
    features: ['24/7 tilgang', 'Tørt og temperert', 'Kodelås'],
    description:
      'Solid bod i bakgården, nyoppusset med tett tak og eget lys. Perfekt for sykler, dekk og sesongutstyr.',
    access: 'Kodelås på porten, egen nøkkel til boden.',
    rules: ['Ikke brannfarlig væske', 'Rydd etter deg'],
    coords: { x: 36, y: 30 },
    host_name: 'Kari Nordmann',
    host_initials: 'KN',
    host_since: '2024',
    host_verified: true,
    host_rating: 4.9,
    host_reviews: 12,
    owner_id: DEMO_USER_ID,
    status: 'active',
    views: 76,
  },
  {
    id: 'l11',
    num: '13',
    title: 'Garasjeplass på Frogner',
    type: 'Garasje',
    city: 'Oslo',
    area: 'Frogner',
    distance: '600 m fra Frognerparken',
    size_m2: 14,
    size_m3: 35,
    price: 1590,
    rating: 5.0,
    reviews: 8,
    ph: 'garasje · 14 m²',
    avail: 'Utleid til 1. sep',
    features: ['Bil-tilgang', 'Egen port', 'Kameraovervåket'],
    description:
      'Plass i felles garasjeanlegg med port og kamera. Tørt hele året, enkel innkjøring fra gateplan.',
    access: 'Portåpner utleveres ved overlevering.',
    rules: ['Kun personbil', 'Ingen lagring av drivstoff'],
    coords: { x: 24, y: 48 },
    host_name: 'Kari Nordmann',
    host_initials: 'KN',
    host_since: '2024',
    host_verified: true,
    host_rating: 5.0,
    host_reviews: 8,
    owner_id: DEMO_USER_ID,
    status: 'rented',
    views: 142,
  },
];

/** Saved by the demo user (the filled hearts). */
export const DEMO_FAVORITE_IDS = ['l1', 'l4'];

export const DEMO_REQUESTS: RequestRow[] = [
  // Incoming — the host inbox on "Mine annonser".
  {
    id: 'r1',
    req_id: 'NL-2026-04812',
    listing_id: 'l10',
    requester_id: 'nabo-jonas',
    from_name: 'Jonas Berg',
    from_phone: '+47 900 12 345',
    message: 'Hei! Trenger plass til sykler og dekk fram til høsten. Er boden ledig fra 1. juni?',
    period_from: '1. juni 2026',
    period_to: '1. okt 2026',
    time_label: '2 timer siden',
    status: 'pending',
    created_at: '2026-05-02T09:12:00.000Z',
  },
  {
    id: 'r2',
    req_id: 'NL-2026-04813',
    listing_id: 'l10',
    requester_id: 'nabo-amina',
    from_name: 'Amina Rashid',
    from_phone: '+47 911 22 333',
    message: 'Flytter i juni og trenger et sted til møbler i noen måneder. Kan jeg komme og se?',
    period_from: '15. juni 2026',
    period_to: '15. sep 2026',
    time_label: 'I går',
    status: 'pending',
    created_at: '2026-05-01T16:40:00.000Z',
  },
  {
    id: 'r3',
    req_id: 'NL-2026-04814',
    listing_id: 'l11',
    requester_id: 'nabo-petter',
    from_name: 'Petter Lund',
    from_phone: '+47 922 33 444',
    message: 'Leter etter garasjeplass til vinterbilen. Tar den gjerne ut året.',
    period_from: '1. mai 2026',
    period_to: '1. sep 2026',
    time_label: '3 dager siden',
    status: 'accepted',
    created_at: '2026-04-29T11:05:00.000Z',
  },
  // Outgoing — the demo user's own tenancy, shown under "Mine leieforhold".
  {
    id: 'r4',
    req_id: 'NL-2026-04803',
    listing_id: 'l3',
    requester_id: DEMO_USER_ID,
    from_name: 'Kari Nordmann',
    from_phone: '+47 933 44 555',
    message: 'Hei! Jeg trenger plass til verkstedutstyr i sommer — er loftet ledig?',
    period_from: '15. mai 2026',
    period_to: '15. aug 2026',
    time_label: 'For en uke siden',
    status: 'accepted',
    created_at: '2026-04-24T08:30:00.000Z',
  },
];
